real_effort/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
import random

doc = """
This is a task that requires real effort from participants.
Subjects are shown two images of incomprehensible text.
Subjects are required to transcribe (copy) the text into a text entry field.
The quality of a subject's transcription is measured by the
<a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein distance</a>.
"""


def levenshtein(a, b):
    """Calculates the Levenshtein distance between a and b."""
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n,m)) space
        a, b = b, a
        n, m = m, n

    current = range(n + 1)
    for i in range(1, m + 1):
        previous, current = current, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete = previous[j] + 1, current[j - 1] + 1
            change = previous[j - 1]
            if a[j - 1] != b[i - 1]:
                change = change + 1
            current[j] = min(add, delete, change)

    return current[n]


def distance_and_ok(transcribed_text, reference_text, max_error_rate):
    error_threshold = len(reference_text) * max_error_rate
    distance = levenshtein(transcribed_text, reference_text)
    ok = distance <= error_threshold
    return distance, ok


class Constants(BaseConstants):
    name_in_url = 'real_effort'
    players_per_group = None

    reference_texts = [
        "Revealed preference",
        "Hex ton satoha egavecen. Loh ta receso minenes da linoyiy xese coreliet ocotine! Senuh asud tu bubo tixorut sola, bo ipacape le rorisin lesiku etutale saseriec niyacin ponim na. Ri arariye senayi esoced behin? Tefid oveve duk mosar rototo buc: Leseri binin nolelar sise etolegus ibosa farare. Desac eno titeda res vab no mes!",
    ]

    num_rounds = len(reference_texts)

    allowed_error_rates = [0, 0.03]


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    transcribed_text = models.LongStringField()
    levenshtein_distance = models.IntegerField()

real_effort/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.api
import otree.forms

import otree.api
from otree.api import Currency as c, currency_range

class Page(otree.api.Page):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):


    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()

class Form(otree.forms.Form):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

class Bot(otree.api.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

real_effort/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from . import models
from ._builtin import Page, WaitPage
from otree.common import Currency as c, currency_range, safe_json
from .models import Constants, levenshtein, text_is_close_enough
from django.conf import settings


def vars_for_all_templates(self):

    return {'paragraph_count': Constants.paragraph_count}


class Transcription1(Page):

    template_name = 'real_effort/Transcription.html'

    form_model = models.Player
    form_fields = ['transcription_1']

    def vars_for_template(self):
        return {
                'number': 1,
                'magic_link': settings.DEBUG and Constants.show_transcription_1,
                'transcription': Constants.reference_texts[0],
                'debug': settings.DEBUG,
                'error_rate_percent': int(100 * Constants.error_rate_transcription_1)

        }

    def transcription_1_error_message(self, text_user):
        if not text_is_close_enough(text_user, Constants.reference_texts[0], Constants.error_rate_transcription_1):
            if Constants.error_rate_transcription_1 == 0.0:
                return Constants.transcription_error_0
            else:
                return Constants.transcription_error_positive
        else:
            self.distance_1 = levenshtein(Constants.reference_texts[0], text_user)


class Transcription2(Page):

    template_name = 'real_effort/Transcription.html'

    form_model = models.Player
    form_fields = ['transcription_2']

    def vars_for_template(self):
        return {'number': 2,
                'magic_link': settings.DEBUG and Constants.show_transcription_2,
                'transcription': Constants.reference_texts[1],
                'error_rate_percent': int(100 * Constants.error_rate_transcription_2)}

    def transcription_2_error_message(self, text_user):
        if not text_is_close_enough(text_user, Constants.reference_texts[1], Constants.error_rate_transcription_2):
            if Constants.error_rate_transcription_2 == 0.0:
                return Constants.transcription_error_0
            else:
                return Constants.transcription_error_positive
        else:
            self.distance_2 = levenshtein(Constants.reference_texts[1], text_user)


class Summary(Page):

    def vars_for_template(self):
        self.player.set_payoff()
        return {
                #'distance_1' : self.player.distance_1,
                'transcription_entered_1' : len(self.player.transcription_1),
                'transcription_length_1' : len(Constants.reference_texts[0]),
                #'distance_2' : self.player.distance_2,
                'transcription_entered_2' : len(self.player.transcription_2),
                'transcription_length_2' : len(Constants.reference_texts[1]),
        }

page_sequence = [Transcription1,
            Transcription2,
            Summary]

real_effort/templates/real_effort/Results 2.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Summary
{% endblock %}

{% block content %}

    <p class="text-success">
        The table below shows some statistics for the transcriptions you have entered. 
        In a real study this table would usually not be shown to subjects.
        <br>
        The <a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein</a> distance is given in the last column.
        Note that the difference between the length of the given text and the length of
        the text entered is a lower bound on the Levenshtein distance.
    </p>

    <div class="panel panel-success">

        <div class="panel-heading">
                Statistics for transcriptions
        </div>

        <table class="table">
            <tr>
                <th>Transcription #</th>
                <th>Length of given text</th>
                <th>Length of text entered</th>
                <th>Levenshtein distance</th>
            </tr>
            {% for row in table_rows %}
            <tr>
                <td>{{ row.round_number }}</td>
                <td>{{ row.reference_text_length }}</td>
                <td>{{ row.transcribed_text_length }}</td>
                <td>{{ row.distance }}</td>
            </tr>
            {% endfor %}

        </table>

    </div>

{% endblock %}

real_effort/templates/real_effort/Results.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Summary
{% endblock %}

{% block content %}

    <p class="text-success">
        The table below shows some statistics for the transcriptions you have entered. 
        In a real study this table would usually not be shown to subjects.
        <br>
        The <a href="http://en.wikipedia.org/wiki/Levenshtein_distance">Levenshtein</a> distance is given in the last column.
        Note that the difference between the length of the given text and the length of
        the text entered is a lower bound on the Levenshtein distance.
    </p>

    <div class="panel panel-success">

        <div class="panel-heading">
                Statistics for transcriptions
        </div>

        <table class="table">
            <tr>
                <th>Transcription #</th>
                <th>Length of given text</th>
                <th>Length of text entered</th>
                <th>Levenshtein distance</th>
            </tr>
            {% for row in table_rows %}
            <tr>
                <td>{{ row.round_number }}</td>
                <td>{{ row.reference_text_length }}</td>
                <td>{{ row.transcribed_text_length }}</td>
                <td>{{ row.distance }}</td>
            </tr>
            {% endfor %}

        </table>

    </div>

{% endblock %}

real_effort/templates/real_effort/Transcribe 2.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcription task {{ subsession.round_number }}/{{ Constants.num_rounds }}
{% endblock %}

{% block content %}

    <p>
        Please transcribe (copy) the text below into the input field.
        Be exact and make sure to get all characters and spaces correct.
    </p>


    <img src="{% static image_path %}"/>
    <br><br>


    {% formfield player.transcribed_text label="" %}

    {% next_button %}

    {% if debug %}
        <div class="card border-warning">
            <div class="card-body">
            <h4>Explanation for researchers (shown in debug mode only)</h4>
            <p>
                You are playing in debug mode, so you can skip the manual
                transcription
                by clicking <a href="#" id="prefill">this link</a>
                and clicking "next".
            </p>

            <p>
                A subject can only advance to the next screen if the
                transcription is {{ required_accuracy }}% accurate.
            </p>
            </div>
        </div>

    {% endif %}
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script>
{% endblock %}

real_effort/templates/real_effort/Transcribe.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcription task {{ subsession.round_number }}/{{ Constants.num_rounds }}
{% endblock %}

{% block content %}

    <p>
        Please transcribe (copy) the text below into the input field.
        Be exact and make sure to get all characters and spaces correct.
    </p>


    <img src="{% static image_path %}"/>
    <br><br>


    {% formfield player.transcribed_text label="" %}

    {% next_button %}

    {% if debug %}
        <div class="card border-warning">
            <div class="card-body">
            <h4>Explanation for researchers (shown in debug mode only)</h4>
            <p>
                You are playing in debug mode, so you can skip the manual
                transcription
                by clicking <a href="#" id="prefill">this link</a>
                and clicking "next".
            </p>

            <p>
                A subject can only advance to the next screen if the
                transcription is {{ required_accuracy }}% accurate.
            </p>
            </div>
        </div>

    {% endif %}
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script>
{% endblock %}

real_effort/templates/real_effort/Transcription.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Transcription task {{ number }}/{{ paragraph_count }}
{% endblock %}

{% block content %}




    <p>
        Please transcribe (that is copy) the text below into the input field. Be exact and make
        sure to get all characters and spaces correct.
    </p>

    <div>
        <img src="{{ STATIC_URL }}paragraphs/new_para{{ number }}.png" />
    </div>

    {% if number == 1 %}
        {% formfield player.transcription_1 with label="" %}
    {% elif number == 2 %}
        {% formfield player.transcription_2 with label="" %}
    {% elif number == 3 %}
        {% formfield player.transcription_3 with label="" %}
    {% endif %}

    {% if magic_link %}
    <script>
    $( document ).ready(function() {
        $('a#prefill').click(function()
        { 
        $('#id_transcription_{{ number }}').val('{{ transcription }}');
        })
    });
    </script>
    <p>
        By the way we have magic <a href="#" id="prefill">link</a> for you.
    </p>
    {% endif %}

    {% next_button %}
    {% if settings.DEBUG %}
    <div class="box papereffect">
        <h4>Explanation for researchers (shown in debug mode only)</h4>
        <p>
        {% if error_rate_percent != 0 %}
        The text has {{ transcription | length }} characters including space.
        A subject can only advance to the next screen if the Levenshtein distance
        is less than {{ error_rate_percent }}% of the total characters.
        {% else %}
        This text is rather short ({{ transcription | length }} characters including space).
        A subject can only advance to the next screen if he makes no mistakes.
        {% endif %}
        </p>
    </div>
    {% endif %}
{% endblock %}